version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/app/
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      # Agrega otras variables de entorno necesarias para Django
    depends_on:
      - db

  frontend:
    build:
        context: ./frontend
        dockerfile: Dockerfile
        args:
          CACHE_INVALIDATOR: ${CACHE_INVALIDATOR:-$(date +%s)}
    command: npm start
    volumes:
      - ./frontend/:/app/
    ports:
      - "3000:3000"
    environment:
      # Agrega variables de entorno necesarias para React
      REACT_APP_BACKEND_URL: http://localhost:8000
    depends_on:
      - backend

volumes:
  postgres_data:
