# Archivo de configuración para Render
services:
  - type: web
    name: cancha-sintetica-frontend
    env: docker
    rootDir: frontend/
    port: 3000
    envVars:
      - key: VITE_API_URL
        value: "https://backend-5e3p.onrender.com" # URL real de tu backend en Render

  - type: web
    name: cancha-sintetica-backend
    env: docker
    rootDir: backend/
    port: 8000
    buildCommand: "pip install -r requirements.txt; python manage.py collectstatic --noinput; python manage.py migrate"
    startCommand: gunicorn --bind 0.0.0.0:8000 --chdir backend cancha.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true # Render puede generar una clave segura
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "backend-5e3p.onrender.com" # URL específica de tu backend en Render
      - key: DATABASE_URL
        value: "postgresql://postgres:databasec123@db.mwceyqtmliuinairkoex.supabase.co:5432/postgres" # Reemplazar con la URL de conexión real de Supabase
