# Archivo de configuración para Render
services:
  - type: web
    name: cancha-sintetica-frontend
    env: docker
    port: 3000
    envVars:
      - key: VITE_API_URL
        value: "https://your-backend-url.onrender.com" # Reemplazar con la URL real de tu backend en Render
