--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: bookings_booking; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bookings_booking (
    id bigint NOT NULL,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    court_id bigint NOT NULL,
    user_id integer NOT NULL,
    payment_id bigint,
    status character varying(20) NOT NULL
);


ALTER TABLE public.bookings_booking OWNER TO postgres;

--
-- Name: bookings_booking_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.bookings_booking ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookings_booking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: courts_court; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.courts_court (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    description text NOT NULL,
    price numeric(10,2) NOT NULL,
    characteristics text NOT NULL,
    empresa_id bigint,
    is_active boolean NOT NULL
);


ALTER TABLE public.courts_court OWNER TO postgres;

--
-- Name: courts_court_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.courts_court ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courts_court_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: courts_courtimage; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.courts_courtimage (
    id bigint NOT NULL,
    image character varying(100) NOT NULL,
    court_id bigint NOT NULL
);


ALTER TABLE public.courts_courtimage OWNER TO postgres;

--
-- Name: courts_courtimage_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.courts_courtimage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courts_courtimage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: empresas_empresa; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.empresas_empresa (
    id bigint NOT NULL,
    nombre character varying(255) NOT NULL,
    direccion text,
    telefono character varying(20),
    email character varying(254)
);


ALTER TABLE public.empresas_empresa OWNER TO postgres;

--
-- Name: empresas_empresa_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.empresas_empresa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.empresas_empresa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments_payment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payments_payment (
    id bigint NOT NULL,
    amount numeric(10,2) NOT NULL,
    payment_date timestamp with time zone NOT NULL,
    booking_id bigint NOT NULL,
    user_id integer NOT NULL,
    gateway_data jsonb,
    method character varying(50) NOT NULL,
    status character varying(20) NOT NULL,
    transaction_id character varying(255)
);


ALTER TABLE public.payments_payment OWNER TO postgres;

--
-- Name: payments_payment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.payments_payment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plans_plan; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.plans_plan (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    description text NOT NULL,
    price numeric(10,2) NOT NULL,
    duration integer NOT NULL,
    auto_renew boolean NOT NULL,
    benefits text NOT NULL,
    discount_percentage numeric(5,2) NOT NULL
);


ALTER TABLE public.plans_plan OWNER TO postgres;

--
-- Name: plans_plan_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.plans_plan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plans_plan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_suscripcionplan; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_suscripcionplan (
    id bigint NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    status character varying(20) NOT NULL,
    auto_renew boolean NOT NULL,
    plan_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.users_suscripcionplan OWNER TO postgres;

--
-- Name: users_suscripcionplan_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_suscripcionplan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_suscripcionplan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    edad integer,
    role character varying(50) NOT NULL,
    empresa_id bigint
);


ALTER TABLE public.users_user OWNER TO postgres;

--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bookings_booking_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bookings_booking
    ADD CONSTRAINT bookings_booking_pkey PRIMARY KEY (id);


--
-- Name: courts_court_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courts_court
    ADD CONSTRAINT courts_court_pkey PRIMARY KEY (id);


--
-- Name: courts_courtimage_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courts_courtimage
    ADD CONSTRAINT courts_courtimage_pkey PRIMARY KEY (id);


--
-- Name: empresas_empresa empresas_empresa_nombre_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empresas_empresa
    ADD CONSTRAINT empresas_empresa_nombre_key UNIQUE (nombre);


--
-- Name: empresas_empresa empresas_empresa_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empresas_empresa
    ADD CONSTRAINT empresas_empresa_pkey PRIMARY KEY (id);


--
-- Name: payments_payment payments_payment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments_payment
    ADD CONSTRAINT payments_payment_pkey PRIMARY KEY (id);


--
-- Name: plans_plan plans_plan_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plans_plan
    ADD CONSTRAINT plans_plan_pkey PRIMARY KEY (id);


--
-- Name: users_suscripcionplan users_suscripcionplan_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_suscripcionplan
    ADD CONSTRAINT users_suscripcionplan_pkey PRIMARY KEY (id);


--
-- Name: users_user users_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_pkey PRIMARY KEY (id);


--
-- Name: users_user users_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_username_key UNIQUE (username);


--
-- Name: bookings_booking_court_id_ca2f87fe; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX bookings_booking_court_id_ca2f87fe ON public.bookings_booking USING btree (court_id);


--
-- Name: bookings_booking_payment_id_c4a0ad11; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX bookings_booking_payment_id_c4a0ad11 ON public.bookings_booking USING btree (payment_id);


--
-- Name: bookings_booking_user_id_834dfc23; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX bookings_booking_user_id_834dfc23 ON public.bookings_booking USING btree (user_id);


--
-- Name: courts_court_empresa_id_987d0886; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX courts_court_empresa_id_987d0886 ON public.courts_court USING btree (empresa_id);


--
-- Name: courts_courtimage_court_id_d24eda51; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX courts_courtimage_court_id_d24eda51 ON public.courts_courtimage USING btree (court_id);


--
-- Name: empresas_empresa_nombre_b99f6da3_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX empresas_empresa_nombre_b99f6da3_like ON public.empresas_empresa USING btree (nombre varchar_pattern_ops);


--
-- Name: payments_payment_booking_id_2a46974b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX payments_payment_booking_id_2a46974b ON public.payments_payment USING btree (booking_id);


--
-- Name: payments_payment_user_id_f9db060a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX payments_payment_user_id_f9db060a ON public.payments_payment USING btree (user_id);


--
-- Name: users_suscripcionplan_plan_id_3e1037e4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_suscripcionplan_plan_id_3e1037e4 ON public.users_suscripcionplan USING btree (plan_id);


--
-- Name: users_suscripcionplan_user_id_ce1c335b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_suscripcionplan_user_id_ce1c335b ON public.users_suscripcionplan USING btree (user_id);


--
-- Name: users_user_empresa_id_199b23a2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_empresa_id_199b23a2 ON public.users_user USING btree (empresa_id);


--
-- Name: users_user_username_06e46fe6_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_username_06e46fe6_like ON public.users_user USING btree (username varchar_pattern_ops);


--
-- Name: bookings_booking bookings_booking_court_id_ca2f87fe_fk_courts_court_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bookings_booking
    ADD CONSTRAINT bookings_booking_court_id_ca2f87fe_fk_courts_court_id FOREIGN KEY (court_id) REFERENCES public.courts_court(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bookings_booking bookings_booking_payment_id_c4a0ad11_fk_payments_payment_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bookings_booking
    ADD CONSTRAINT bookings_booking_payment_id_c4a0ad11_fk_payments_payment_id FOREIGN KEY (payment_id) REFERENCES public.payments_payment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bookings_booking bookings_booking_user_id_834dfc23_fk_auth_user_idxd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bookings_booking
    ADD CONSTRAINT bookings_booking_user_id_834dfc23_fk_auth_user_idxd FOREIGN KEY (user_id) REFERENCES public.users_user(id) NOT VALID;


--
-- Name: courts_court courts_court_empresa_id_987d0886_fk_users_empresa_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courts_court
    ADD CONSTRAINT courts_court_empresa_id_987d0886_fk_users_empresa_id FOREIGN KEY (empresa_id) REFERENCES public.empresas_empresa(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: courts_courtimage courts_courtimage_court_id_d24eda51_fk_courts_court_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courts_courtimage
    ADD CONSTRAINT courts_courtimage_court_id_d24eda51_fk_courts_court_id FOREIGN KEY (court_id) REFERENCES public.courts_court(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payments_payment payments_payment_booking_id_2a46974b_fk_bookings_booking_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments_payment
    ADD CONSTRAINT payments_payment_booking_id_2a46974b_fk_bookings_booking_id FOREIGN KEY (booking_id) REFERENCES public.bookings_booking(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payments_payment payments_payment_user_id_f9db060a_fk_auth_user_idx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments_payment
    ADD CONSTRAINT payments_payment_user_id_f9db060a_fk_auth_user_idx FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_suscripcionplan users_suscripcionplan_plan_id_3e1037e4_fk_plans_plan_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_suscripcionplan
    ADD CONSTRAINT users_suscripcionplan_plan_id_3e1037e4_fk_plans_plan_id FOREIGN KEY (plan_id) REFERENCES public.plans_plan(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_suscripcionplan users_suscripcionplan_user_id_ce1c335b_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_suscripcionplan
    ADD CONSTRAINT users_suscripcionplan_user_id_ce1c335b_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user users_user_empresa_id_199b23a2_fk_users_empresa_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_empresa_id_199b23a2_fk_users_empresa_id FOREIGN KEY (empresa_id) REFERENCES public.empresas_empresa(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--
