# Generated by Django 5.2 on 2025-04-24 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_plan_auto_renew_plan_benefits_and_more'),
        ('users', '0002_alter_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuscripcionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Activa'), ('expired', 'Expirada'), ('cancelled', 'Cancelada')], default='active', max_length=20)),
                ('auto_renew', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='plans.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='users.user')),
            ],
        ),
    ]
