# Generated by Django 5.2 on 2025-05-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_suscripcionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('adminglobal', 'Administrador Global'), ('admin', 'Administrador de Cancha'), ('cliente', 'Cliente')], default='cliente', max_length=20),
        ),
    ]
